--IN THIS WE ARE CREATING TABLES AND MAINTAINING ENTITY RELATIONSHIPS BETWEEN THEM USING KEYS
--CREATING TABLE ORDERS

CREATE TABLE ORDERS(
order_id INT PRIMARY KEY,
customer_id	INT,
restaurant_id INT,
order_item VARCHAR(100),
order_date DATE NOT NULL,
order_time TIME NOT NULL,
order_status VARCHAR(20) DEFAULT 'Pending',
total_amount DECIMAL(10,2) NOT NULL,
CONSTRAINT ORDERS_FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMERS(CUSTOMER_ID),
CONSTRAINT ORDERS_FK_RESTAURANT_ID FOREIGN KEY (RESTAURANT_ID)
REFERENCES RESTAURANTS(RESTAURANT_ID)
);

--CREATING TABLE RESTAURANTS

CREATE TABLE RESTAURANTS(
restaurant_id INT PRIMARY KEY,
restaurant_name	VARCHAR(50) NOT NULL,
city VARCHAR(30),
opening_hours TIME
);

--CREATING TABLE RIDERS

CREATE TABLE RIDERS(
rider_id int primary key,
rider_name varchar(100) NOT NULL,
sign_up date
);

--CREATING TABLE DELIVERIES

CREATE TABLE DELIVERIES(
delivery_id INT PRIMARY KEY,
order_id INT,
delivery_status VARCHAR(100) DEFAULT 'Pending',
delivery_time TIME,
rider_id INT,
CONSTRAINT DELIVERIES_FK_ORDER_ID FOREIGN KEY(ORDER_ID)
REFERENCES ORDERS(ORDER_ID),
CONSTRAINT DELIVERIES_FK_RIDER_ID FOREIGN KEY(RIDER_ID)
REFERENCES RIDERS(RIDER_ID)
);

--CREATING TABLE CUSTOMERS

CREATE TABLE CUSTOMERS(
customer_id INT PRIMARY KEY,
customer_name VARCHAR(100) NOT NULL,
reg_date DATE
);
 
DROP TABLE IF EXISTS deliveries;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS riders;

ALTER TABLE restaurants
ALTER COLUMN OPENING_HOURS TYPE VARCHAR(100);
