--EXPLORATORY DATA ANALYSIS 

SELECT * FROM CATEGORY;
SELECT * FROM CUSTOMER;
SELECT * FROM INVENTORY;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM ORDERS;
SELECT * FROM PAYMENT;
SELECT * FROM PRODUCTS;
SELECT * FROM SELLER;
SELECT * FROM SHIPPING;


SELECT DISTINCT PAYMENT_STATUS FROM PAYMENT;

SELECT * FROM PRODUCTS;
SELECT * FROM SHIPPING WHERE RETURN_DATE IS NOT NULL;

--CHECKING THE DETAILS OF THE ORDER_ID '6747'

SELECT * FROM ORDERS WHERE ORDER_ID='6747' ;
SELECT * FROM PAYMENT  WHERE ORDER_ID='6747' ;